# Generated by Django 4.0.2 on 2022-03-28 10:37

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='cert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='nombre')),
                ('last_name', models.CharField(max_length=20, verbose_name='nombre corto')),
                ('texto', ckeditor.fields.RichTextField()),
                ('dni', models.CharField(max_length=9, unique=True, verbose_name='dni')),
            ],
        ),
    ]
