# Generated by Django 4.0.2 on 2022-04-08 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='cert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='nombre')),
                ('last_name1', models.CharField(max_length=20, verbose_name='apellido1')),
                ('last_name2', models.CharField(max_length=20, verbose_name='apellido2')),
                ('texto', models.CharField(max_length=256, verbose_name='texto')),
                ('dni', models.CharField(max_length=9, unique=True, verbose_name='dni')),
            ],
        ),
    ]
